project_id = "ybzyhhhfykvbxakbrspf"

[functions.generate-questions]
verify_jwt = false

[functions.generate-recommendations]
verify_jwt = false

[functions.confirm-attendance]
verify_jwt = false

[functions.fetch-bilesu-events]
verify_jwt = false

[functions.get-discoverable-users]
verify_jwt = false